### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by EnuDelrum** [rangdevelopment/root-tracker#5]
First, it would be nice to get desktop notifications when a new event is called (like how Idle Notifier works). This would make forestry more AFK while not missing out on new events.

Secondly, it'd be nice to have the option to see events/get notifications for roots only instead of both roots and saps.

**Comment by rangdevelopment** [comment]
thanks! I'll have a look at implementing this

**Comment by rangdevelopment** [comment]
done, this will be available in the next update. you may toggle event types in the settings.
